name: Python package

on: [push]
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version:
          ["3.10", "3.11", "3.12", "3.13", "pypy3.11"]
        experimental: [false]
        include:
          - python-version: "3.13"
            os: ubuntu-24.04-arm
            experimental: false
          - python-version: "3.13"
            os: windows-11-arm
            experimental: false
          - python-version: "3.14"
            os: ubuntu-latest
            experimental: true
          - python-version: "3.14"
            os: ubuntu-24.04-arm
            experimental: true
          - python-version: "3.14t"
            os: ubuntu-latest
            experimental: true
          - python-version: "3.14t"
            os: ubuntu-24.04-arm
            experimental: true
          - python-version: "3.14t"
            os: windows-latest
            experimental: true
          - python-version: "3.14t"
            os: windows-11-arm
            experimental: true
          - python-version: "3.14t"
            os: macos-latest
            experimental: true
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
          cache: pip
      - name: tox-gh workaround for freethreaded
        if: ${{ matrix.python-version == '3.14t' }}
        run: echo "TOX_GH_MAJOR_MINOR=3.14t" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          python3 -m pip install 'tox' 'tox-gh'
          tox --version
      - name: Install native deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y mecab libmecab-dev mecab-ipadic-utf8
      - name: Test with tox
        run: |
          tox
